name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us reproduce and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify you have completed these steps before submitting
      options:
        - label: I have searched for existing issues that might be related
          required: true
        - label: I have read the documentation and README
          required: true
        - label: I am using the latest version of the module
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize CardanoProtocol with...
        2. Call method...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: 💻 Code Sample
      description: Minimal code sample that reproduces the issue
      render: typescript
      placeholder: |
        import { CardanoProtocol } from '@airgap/cardano';

        const protocol = new CardanoProtocol();
        // Your code here...

  - type: textarea
    id: error-logs
    attributes:
      label: 📝 Error Logs
      description: Any error messages or stack traces
      render: text
      placeholder: Paste error logs here...

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity Level
      description: How severe is this bug?
      options:
        - "🔴 Critical - Blocks core functionality"
        - "🟠 High - Significant impact on functionality"
        - "🟡 Medium - Some functionality affected"
        - "🟢 Low - Minor issue or cosmetic"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🎯 Component
      description: Which component is affected?
      options:
        - "Protocol Core"
        - "Transaction Builder"
        - "UTXO Selector"
        - "QR Serialization"
        - "Address Generation"
        - "Cryptographic Operations"
        - "Security Utilities"
        - "Type Definitions"
        - "Documentation"
        - "Tests"
        - "Other"
    validations:
      required: true

  - type: input
    id: environment-node
    attributes:
      label: Node.js Version
      description: Output of `node --version`
      placeholder: "v20.x.x"
    validations:
      required: true

  - type: input
    id: environment-npm
    attributes:
      label: NPM Version
      description: Output of `npm --version`
      placeholder: "x.x.x"
    validations:
      required: true

  - type: input
    id: environment-os
    attributes:
      label: Operating System
      description: Your operating system and version
      placeholder: "Ubuntu 22.04 / macOS 13.0 / Windows 11"
    validations:
      required: true

  - type: input
    id: module-version
    attributes:
      label: Module Version
      description: Version of @airgap/cardano being used
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Any other context about the problem
      placeholder: |
        - Related issues
        - Workarounds tried
        - Impact on your project
        - Any other relevant information

  - type: checkboxes
    id: security
    attributes:
      label: 🔒 Security Consideration
      description: Security-related information
      options:
        - label: This bug involves security-sensitive information (private keys, sensitive data)
        - label: This bug could potentially be exploited maliciously
        - label: I have NOT included any private keys or sensitive data in this report

  - type: markdown
    attributes:
      value: |
        ## 🚀 Next Steps

        After submitting this issue:
        1. Our team will review and triage the bug report
        2. We may ask for additional information or clarification
        3. Security-related bugs will be handled with priority
        4. You can track progress through issue comments and labels

        **Thank you for helping improve the AirGap Cardano module!** 🙏
